# SPDX-License-Identifier: Apache-2.0
"""Browser tests for the img2live viewer: headless Chrome with software WebGL2 (SwiftShader).

Needs: playwright (python), /usr/bin/google-chrome and the sample puppet (see CHROME_PATH / SAMPLE below).
The sample is generated by the rig compiler; when it is missing the tests are skipped with a reason.
"""
from __future__ import annotations

import http.server
import importlib.util
import io
import json
import os
import socketserver
import sys
import threading
from pathlib import Path

import numpy as np
import pytest

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
STATIC = ROOT / "src" / "img2live" / "web" / "static"
# The default sample is compiled from the synthetic character (license-clean, no GPU).  To test against a real
# puppet compiled from an actual job, point IMG2LIVE_TEST_PUPPET at a directory holding puppet.json + tex/.
SAMPLE = Path(os.environ.get("IMG2LIVE_TEST_PUPPET") or ROOT / "bench" / "outputs" / "puppet_synthetic")
SHOTS = ROOT / "bench" / "outputs" / "viewer_shots"
RUNTIME_PY = ROOT / "src" / "img2live" / "rig" / "runtime_py.py"

CHROME_PATH = os.environ.get("IMG2LIVE_CHROME", "/usr/bin/google-chrome")
CHROME_ARGS = [
    "--use-gl=angle",
    "--use-angle=swiftshader",
    "--enable-unsafe-swiftshader",
    "--ignore-gpu-blocklist",
    "--no-sandbox",
]

sync_api = pytest.importorskip("playwright.sync_api", reason="playwright is not installed")
if not Path(CHROME_PATH).exists():
    pytest.skip(f"{CHROME_PATH} not found (set IMG2LIVE_CHROME)", allow_module_level=True)
if not (SAMPLE / "puppet.json").exists():
    sys.path.insert(0, str(ROOT / "src"))
    import numpy as _np

    from img2live.engine.fake import FakeDecomposer
    from img2live.rig.compile import compile_puppet
    from img2live.rig.layers import build_layers
    from img2live.rig.spec import parse_prompt

    _r = FakeDecomposer().run(_np.zeros((10, 10, 4), _np.uint8))
    compile_puppet(build_layers(_r.layers, _r.head_hires, _r.head_square), parse_prompt(""), out_dir=str(SAMPLE))

sys.path.insert(0, str(HERE))
import make_shots  # same directory

# ------------------------------------------------------------------------------------------------ helpers
_spec = importlib.util.spec_from_file_location("img2live_runtime_py", RUNTIME_PY)
runtime_py = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(runtime_py)  # numpy only: avoids importing the heavy img2live package


class _Handler(http.server.SimpleHTTPRequestHandler):
    static_dir = ""
    sample_dir = ""

    def translate_path(self, path):  # /sample/* -> sample puppet, everything else -> static dir
        path = path.split("?", 1)[0].split("#", 1)[0]
        if path.startswith("/sample/"):
            return os.path.join(self.sample_dir, path[len("/sample/"):])
        return os.path.join(self.static_dir, path.lstrip("/"))

    def end_headers(self):
        self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def log_message(self, *args):
        pass


class _Server(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True


def serve(static_dir: Path, sample_dir: Path):
    handler = type("Handler", (_Handler,), {"static_dir": str(static_dir), "sample_dir": str(sample_dir)})
    srv = _Server(("127.0.0.1", 0), handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv, f"http://127.0.0.1:{srv.server_address[1]}"


@pytest.fixture(scope="module")
def base_url():
    srv, url = serve(STATIC, SAMPLE)
    yield url
    srv.shutdown()


@pytest.fixture(scope="module")
def browser():
    with sync_api.sync_playwright() as p:
        b = p.chromium.launch(executable_path=CHROME_PATH, headless=True, args=CHROME_ARGS)
        yield b
        b.close()


class Page:
    """A page with every console error / failed request / page error recorded."""

    def __init__(self, context, base_url):
        self.context = context
        self.base_url = base_url
        self.page = context.new_page()
        self.errors: list[str] = []
        self.warnings: list[str] = []
        p = self.page
        p.on("console", self._on_console)
        p.on("pageerror", lambda e: self.errors.append(f"pageerror: {e}"))
        p.on("requestfailed", lambda r: self.errors.append(f"requestfailed: {r.url} {r.failure}"))
        p.on("response", lambda r: self.errors.append(f"HTTP {r.status}: {r.url}") if r.status >= 400 else None)

    def _on_console(self, m):
        if m.type == "error":
            self.errors.append(f"console.error: {m.text}")
        elif m.type == "warning":
            self.warnings.append(m.text)

    def open(self, query=make_shots.QUIET, expect_ready=True):
        self.page.goto(f"{self.base_url}/viewer-test.html?{query}")
        self.page.wait_for_function("document.documentElement.dataset.ready", timeout=30000)
        if expect_ready:
            assert self.page.evaluate("document.documentElement.dataset.ready") == "1", self.page.evaluate("window.__img2liveError")
        make_shots.settle(self.page)
        return self

    def __getattr__(self, name):
        return getattr(self.page, name)


@pytest.fixture()
def viewer(browser, base_url):
    ctx = browser.new_context(viewport={"width": 1280, "height": 800})
    v = Page(ctx, base_url)
    yield v
    ctx.close()


def canvas_pixels(page) -> np.ndarray:
    """Screenshot of the canvas area as an RGB uint8 array."""
    from PIL import Image

    png = page.locator(".i2l-canvas").screenshot()
    return np.array(Image.open(io.BytesIO(png)).convert("RGB"))


def puppet_json() -> dict:
    return json.loads((SAMPLE / "puppet.json").read_text(encoding="utf8"))


# ------------------------------------------------------------------------------------------------ (1) loading
def test_loads_without_console_errors_or_failed_requests(viewer):
    viewer.open("")  # default options: idle, blink and physics running
    viewer.page.wait_for_timeout(1200)
    assert viewer.page.locator(".i2l-canvas").count() == 1
    assert viewer.page.locator(".i2l-banner").is_hidden()
    assert viewer.errors == []
    assert [w for w in viewer.warnings if "img2live" in w] == []


def test_default_puppet_url_is_the_sample(viewer):
    viewer.open("")
    assert viewer.page.evaluate("window.__img2live.model.meshes.length") == len(puppet_json()["meshes"])


# ------------------------------------------------------------------------------------------------ (2) pixels
def test_canvas_has_non_background_pixels(viewer):
    viewer.open(make_shots.QUIET + "&bg=white")
    img = canvas_pixels(viewer.page)
    non_bg = np.any(img != 255, axis=2).mean()
    assert non_bg > 0.03, f"only {non_bg:.1%} of the canvas differs from the white background"
    # WebGL side: same check straight from the framebuffer (alpha is opaque for solid backgrounds)
    px = viewer.page.evaluate(
        "() => { const r = window.__img2live.renderer.readPixels(); let n = 0;"
        " for (let i = 0; i < r.data.length; i += 4) if (r.data[i] !== 255 || r.data[i+1] !== 255 || r.data[i+2] !== 255) n++;"
        " return [n, r.width * r.height]; }"
    )
    assert px[0] / px[1] > 0.03


def test_stencil_buffer_exists(viewer):
    viewer.open()
    bits = viewer.page.evaluate("() => { const gl = window.__img2live.renderer.gl; return [gl.getParameter(gl.STENCIL_BITS), gl.getContextAttributes().stencil]; }")
    assert bits[0] >= 8 and bits[1] is True


# ------------------------------------------------------------------------------------------------ (3) parity
PARAM_SETS = {
    "rest": {},
    "AngleX+30": {"ParamAngleX": 30},
    "AngleX-30": {"ParamAngleX": -30},
    "AngleY+30": {"ParamAngleY": 30},
    "AngleZ20+Body10": {"ParamAngleZ": 20, "ParamBodyAngleX": 10},
    "EyeLOpen0": {"ParamEyeLOpen": 0},
    "Gaze1+AngleX-20": {"ParamEyeBallX": 1, "ParamAngleX": -20},
    "Mouth1": {"ParamMouthOpenY": 1},
    "HairBack1": {"ParamHairBack": 1},
    # in-between values exercise the piecewise-linear interpolation
    "mixed": {"ParamAngleX": 11.5, "ParamAngleY": -7, "ParamAngleZ": -13, "ParamBodyAngleZ": 6, "ParamBreath": 0.37,
              "ParamEyeROpen": 0.3, "ParamEyeBallY": -0.4, "ParamBrowLY": 0.6, "ParamMouthOpenY": 0.02,
              "ParamHairFront": -0.55, "ParamTailSway": 0.5},
}

JS_EVAL = """
(sets) => {
  const { model, viewer, controller, renderer } = window.__img2live;
  viewer.setOption('idle', false); viewer.setOption('blink', false); viewer.setOption('physics', false);
  const meshes = model.meshes;
  const grab = (vals, how) => Object.fromEntries(meshes.map((m, i) => {
    const out = new Float32Array(m.positions.length);
    if (how === 'gpu') return [m.id, Array.from(renderer.debugReadPositions(i))];
    model.evaluateMesh(i, vals, out);
    return [m.id, Array.from(out)];
  }));
  const res = { direct: [], controller: [], gpu: [], opacity: [] };
  for (const s of sets) {
    res.direct.push(grab(s, 'cpu'));                       // plain {id: value} object
    viewer.resetParams();
    for (const [k, v] of Object.entries(s)) viewer.setParam(k, v);
    controller.step(0.016);                                // user -> idle/blink/physics (all off) -> clamp
    res.controller.push(grab(controller.values, 'cpu'));
    renderer.render(controller.values);                    // evaluates + uploads dirty meshes
    res.gpu.push(grab(null, 'gpu'));                       // read the GPU buffers back
    res.opacity.push(Object.fromEntries(meshes.map((m, i) => [m.id, model.opacityOf(i, controller.values)])));
  }
  viewer.resetParams();
  return res;
}
"""


def _max_err(js_meshes: dict, ref: dict) -> float:
    assert set(js_meshes) == set(ref)
    worst = 0.0
    for mid, arr in js_meshes.items():
        a = np.asarray(arr, dtype=np.float64).reshape(-1, 2)
        assert a.shape == ref[mid].shape, mid
        worst = max(worst, float(np.abs(a - ref[mid]).max()))
    return worst


def test_numeric_parity_with_python_reference(viewer):
    viewer.open()
    puppet = puppet_json()
    names = list(PARAM_SETS)
    res = viewer.page.evaluate(JS_EVAL, [PARAM_SETS[n] for n in names])
    for k, name in enumerate(names):
        ref = runtime_py.evaluate(puppet, PARAM_SETS[name])
        full = {p["id"]: p["default"] for p in puppet["params"]}
        full.update(PARAM_SETS[name])
        for path in ("direct", "controller", "gpu"):
            err = _max_err(res[path][k], ref)
            assert err < 1e-3, f"{name} via {path}: max vertex error {err:.5f} px"
        for m in puppet["meshes"]:  # opacity, incl. the mouth overlay's opacityBind
            assert res["opacity"][k][m["id"]] == pytest.approx(runtime_py.opacity_of(m, full), abs=1e-6), (name, m["id"])
    assert len(names) >= 6
    assert set(res["direct"][0]) == {m["id"] for m in puppet["meshes"]}


def test_sign_conventions(viewer):
    """+AngleX turns the head to the viewer's right, +AngleY looks up, +AngleZ tilts clockwise on screen."""
    viewer.open()
    res = viewer.page.evaluate(
        """() => {
          const { model } = window.__img2live;
          const centroid = (id, params) => { const i = model.meshIndex.get(id), o = new Float32Array(model.meshes[i].positions.length);
            model.evaluateMesh(i, params, o); let x = 0, y = 0; for (let k = 0; k < o.length; k += 2) { x += o[k]; y += o[k + 1]; }
            return [x / (o.length / 2), y / (o.length / 2)]; };
          const r = {};
          for (const id of ['nose', 'eyewhite_l', 'eyewhite_r', 'mouth']) {
            const a = centroid(id, {}), x = centroid(id, { ParamAngleX: 30 }), y = centroid(id, { ParamAngleY: 30 });
            r[id] = { dx: x[0] - a[0], dy: y[1] - a[1] };
          }
          // roll: a point above the pivot (hair top) moves right = clockwise on screen (y down)
          const top = centroid('front_hair', {}), rolled = centroid('front_hair', { ParamAngleZ: 25 });
          r.roll = { dx: rolled[0] - top[0] };
          return r;
        }"""
    )
    for mesh in ("nose", "eyewhite_l", "eyewhite_r", "mouth"):
        assert res[mesh]["dx"] > 3, (mesh, res[mesh])  # features move right for +AngleX
        assert res[mesh]["dy"] < -2, (mesh, res[mesh])  # ... and up for +AngleY
    assert res["roll"]["dx"] > 5  # hair (above the neck pivot) swings right: clockwise


def test_physics_and_idle_are_clamped_and_bounded(viewer):
    """Run the controller for a minute of simulated time with everything on: values stay in range, nothing explodes."""
    viewer.open("")
    res = viewer.page.evaluate(
        """() => {
          const { controller: c, model } = window.__img2live;
          for (const o of ['idle', 'blink', 'physics']) c.setOption(o, true);
          let bad = 0, maxHair = 0, minOpen = 1;
          const hair = model.paramIndex.get('ParamHairBack'), eye = model.paramIndex.get('ParamEyeLOpen');
          for (let t = 0; t < 60 * 60; t++) {
            if (t % 300 === 0) c.setParam('ParamAngleX', (Math.random() * 2 - 1) * 30);   // user swings the head
            const v = c.step(1 / 60);
            for (let i = 0; i < v.length; i++) if (!(v[i] >= model.mins[i] - 1e-9 && v[i] <= model.maxs[i] + 1e-9)) bad++;
            maxHair = Math.max(maxHair, Math.abs(v[hair])); minOpen = Math.min(minOpen, v[eye]);
          }
          c.reset();
          return { bad, maxHair, minOpen };
        }"""
    )
    assert res["bad"] == 0
    assert 0.05 < res["maxHair"] <= 1.0  # the hair does move, within its limit
    assert res["minOpen"] < 0.1  # at least one blink closed the eye


def test_runtime_is_importable_without_dom(tmp_path):
    """puppet-runtime.js must not touch the DOM or WebGL: load it in Node when Node is available."""
    import shutil
    import subprocess

    node = shutil.which("node")
    if not node:
        pytest.skip("node is not installed")
    mjs = tmp_path / "puppet-runtime.mjs"
    mjs.write_text((STATIC / "js" / "puppet-runtime.js").read_text(encoding="utf8"), encoding="utf8")
    script = tmp_path / "check.mjs"
    ref = runtime_py.evaluate(puppet_json(), PARAM_SETS["mixed"])
    (tmp_path / "ref.json").write_text(json.dumps({k: v.reshape(-1).tolist() for k, v in ref.items()}))
    script.write_text(
        f"""
import fs from 'fs';
import {{ PuppetModel, PuppetController }} from {json.dumps(mjs.as_uri())};
const m = new PuppetModel(JSON.parse(fs.readFileSync({json.dumps(str(SAMPLE / 'puppet.json'))}, 'utf8')));
const ref = JSON.parse(fs.readFileSync({json.dumps(str(tmp_path / 'ref.json'))}, 'utf8'));
const params = {json.dumps(PARAM_SETS['mixed'])};
let worst = 0;
m.meshes.forEach((mesh, i) => {{
  const out = new Float32Array(mesh.positions.length); m.evaluateMesh(i, params, out);
  ref[mesh.id].forEach((v, k) => {{ worst = Math.max(worst, Math.abs(v - out[k])); }});
}});
const c = new PuppetController(m, {{ seed: 1 }});
for (let t = 0; t < 600; t++) c.step(1 / 60);
console.log(JSON.stringify({{ worst, ok: typeof document === 'undefined' }}));
"""
    )
    r = subprocess.run([node, str(script)], capture_output=True, text=True, timeout=60, check=False)
    assert r.returncode == 0, r.stderr
    out = json.loads(r.stdout.strip().splitlines()[-1])
    assert out["ok"] and out["worst"] < 1e-3


# ------------------------------------------------------------------------------------------------ (4) interaction
def test_slider_changes_pixels(viewer):
    viewer.open(make_shots.QUIET + "&camera=head")
    before = canvas_pixels(viewer.page)
    slider = viewer.page.locator('input[data-param="ParamAngleX"]')
    slider.focus()
    slider.press("End")  # keyboard on the real control: fires `input`, drives the param to +30
    make_shots.settle(viewer.page)
    assert viewer.page.evaluate("window.__img2live.viewer.getParams().ParamAngleX") == pytest.approx(30, abs=0.2)
    after = canvas_pixels(viewer.page)
    changed = np.any(before != after, axis=2).mean()
    assert changed > 0.01, f"only {changed:.2%} of the pixels changed"
    assert viewer.errors == []


def test_layer_toggle_hides_the_layer(viewer):
    viewer.open(make_shots.QUIET + "&camera=head&bg=white")
    before = canvas_pixels(viewer.page)
    box = viewer.page.locator(".i2l-layer", has=viewer.page.locator(".i2l-layer-name", has_text="front_hair")).locator("input[type=checkbox]")
    box.uncheck()
    make_shots.settle(viewer.page)
    after = canvas_pixels(viewer.page)
    assert np.any(before != after, axis=2).mean() > 0.05
    box.check()
    make_shots.settle(viewer.page)
    assert np.array_equal(before, canvas_pixels(viewer.page)), "re-enabling the layer must restore the exact picture"
    # solo: everything else disappears
    viewer.page.locator(".i2l-layer", has=viewer.page.locator(".i2l-layer-name", has_text="nose")).get_by_role("button", name="Solo").click()
    make_shots.settle(viewer.page)
    solo = canvas_pixels(viewer.page)
    assert np.any(solo != 255, axis=2).mean() < np.any(before != 255, axis=2).mean() * 0.5


def test_snapshot_png(viewer):
    viewer.open(make_shots.QUIET)
    data = viewer.page.evaluate(
        "async () => { const b = await window.__img2live.viewer.snapshotPNG(); return { type: b.type, bytes: Array.from(new Uint8Array(await b.arrayBuffer())) }; }"
    )
    assert data["type"] == "image/png"
    raw = bytes(data["bytes"])
    assert raw[:8] == b"\x89PNG\r\n\x1a\n" and len(raw) > 2000
    from PIL import Image

    img = Image.open(io.BytesIO(raw)).convert("RGBA")
    a = np.array(img)
    w, h = viewer.page.evaluate("[window.__img2live.renderer.canvas.width, window.__img2live.renderer.canvas.height]")
    assert img.size == (w, h)
    assert (a[..., 3] > 0).mean() > 0.03  # the character
    assert a[0, 0, 3] == 0  # checkerboard background -> transparent PNG
    # the on-screen canvas is still drawn afterwards
    assert viewer.page.evaluate("window.__img2live.renderer.stats.drawCalls") > 5


def test_snapshot_button_downloads_a_png(viewer):
    viewer.open(make_shots.QUIET)
    with viewer.page.expect_download() as d:
        viewer.page.get_by_role("button", name="PNG").click()
    path = d.value.path()
    assert d.value.suggested_filename.endswith(".png")
    assert Path(path).read_bytes()[:8] == b"\x89PNG\r\n\x1a\n"


def _recording_supported(page) -> bool:
    return page.evaluate(
        "() => typeof MediaRecorder !== 'undefined' && !!HTMLCanvasElement.prototype.captureStream"
        " && ['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].some((t) => MediaRecorder.isTypeSupported(t))"
    )


def test_recording_produces_a_webm(viewer):
    viewer.open("")  # idle on, so frames keep changing
    if not _recording_supported(viewer.page):
        pytest.skip("MediaRecorder with a webm mimeType is not supported by this headless Chrome")
    res = viewer.page.evaluate(
        """async () => {
          const v = window.__img2live.viewer;
          v.startRecording();
          const during = v.recording;
          await new Promise((r) => setTimeout(r, 1500));
          const blob = await v.stopRecording();
          const head = new Uint8Array(await blob.slice(0, 4).arrayBuffer());
          return { during, after: v.recording, size: blob.size, type: blob.type, head: Array.from(head) };
        }"""
    )
    assert res["during"] is True and res["after"] is False
    assert res["size"] > 1000, res
    assert res["type"].startswith("video/webm")
    assert res["head"] == [0x1A, 0x45, 0xDF, 0xA3]  # EBML magic
    assert viewer.errors == []


def test_record_button_downloads_a_webm(viewer):
    viewer.open("")
    if not _recording_supported(viewer.page):
        pytest.skip("MediaRecorder with a webm mimeType is not supported by this headless Chrome")
    btn = viewer.page.get_by_role("button", name="Record")
    btn.click()
    assert viewer.page.locator(".i2l-rec").get_attribute("aria-pressed") == "true"
    viewer.page.wait_for_timeout(1200)
    with viewer.page.expect_download() as d:
        viewer.page.locator(".i2l-rec").click()
    assert d.value.suggested_filename.endswith(".webm")
    assert Path(d.value.path()).stat().st_size > 1000


def test_space_toggles_idle_and_switches_work(viewer):
    viewer.open("")
    idle = viewer.page.get_by_role("switch", name="Idle motion")
    assert idle.is_checked()
    viewer.page.locator(".i2l-canvas").focus()
    viewer.page.keyboard.press("Space")
    assert not idle.is_checked()
    assert viewer.page.evaluate("window.__img2live.viewer.getOption('idle')") is False
    viewer.page.keyboard.press("Space")
    assert idle.is_checked()
    # wireframe switch reaches the renderer
    viewer.page.get_by_role("switch", name="Wireframe").check()
    assert viewer.page.evaluate("window.__img2live.renderer.wireframe") is True


def test_driven_params_are_locked_while_physics_is_on(viewer):
    viewer.open("physics=1&idle=0&blink=0")
    hair = viewer.page.locator('input[data-param="ParamHairBack"]')
    assert hair.is_disabled()
    assert viewer.page.locator('input[data-param="ParamAngleX"]').is_enabled()
    viewer.page.get_by_role("switch", name="Physics").uncheck()
    assert hair.is_enabled()


def test_physics_moves_the_hair_when_the_head_turns(viewer):
    viewer.open("physics=1&idle=0&blink=0")
    peak = viewer.page.evaluate(
        """async () => {
          const v = window.__img2live.viewer, c = window.__img2live.controller;
          v.setParam('ParamAngleX', 0);
          let peak = 0;
          const t0 = performance.now();
          v.setParam('ParamAngleX', 25);
          while (performance.now() - t0 < 1500) { await new Promise(requestAnimationFrame); peak = Math.max(peak, Math.abs(c.getParam('ParamHairBack'))); }
          return peak;
        }"""
    )
    assert peak > 0.05


GAZE_OFFSET_JS = """() => {
  const { model, controller } = window.__img2live;
  const c = (id) => { const i = model.meshIndex.get(id), o = new Float32Array(model.meshes[i].positions.length);
    model.evaluateMesh(i, controller.values, o); let x = 0, y = 0; for (let k = 0; k < o.length; k += 2) { x += o[k]; y += o[k + 1]; }
    return [x / (o.length / 2), y / (o.length / 2)]; };
  const a = c('irides_l'), b = c('eyewhite_l');
  return [a[0] - b[0], a[1] - b[1]];
}"""


def test_mouse_follow_steers_head_and_gaze(viewer):
    viewer.open("follow=1&idle=0&blink=0&physics=0&camera=head")
    box = viewer.page.locator(".i2l-canvas").bounding_box()
    viewer.page.mouse.move(box["x"] + box["width"] * 0.95, box["y"] + box["height"] * 0.1)
    viewer.page.wait_for_timeout(1200)
    p = viewer.page.evaluate("window.__img2live.viewer.getParams()")
    assert p["ParamAngleX"] > 5, p  # cursor on the right -> head turns to the viewer's right
    assert p["ParamAngleY"] > 2, p  # cursor above -> head looks up
    assert p["ParamEyeBallX"] > 0.3, p
    viewer.page.mouse.move(box["x"] + box["width"] * 0.05, box["y"] + box["height"] * 0.9)
    viewer.page.wait_for_timeout(1200)
    p = viewer.page.evaluate("window.__img2live.viewer.getParams()")
    assert p["ParamAngleX"] < -5 and p["ParamAngleY"] < -2, p
    # the gaze itself (iris position inside the eye white) must follow the cursor, whatever sign the data uses
    viewer.page.mouse.move(box["x"] + box["width"] * 0.95, box["y"] + box["height"] * 0.05)
    viewer.page.wait_for_timeout(1200)
    off = viewer.page.evaluate(GAZE_OFFSET_JS)
    viewer.page.mouse.move(box["x"] - 50, box["y"] - 50)
    viewer.page.wait_for_timeout(1500)
    rest = viewer.page.evaluate(GAZE_OFFSET_JS)
    assert off[0] - rest[0] > 3, (off, rest)  # iris moved right inside the eye
    assert off[1] - rest[1] < -1.5, (off, rest)  # ... and up (screen y is down)
    viewer.page.mouse.move(box["x"] - 50, box["y"] - 50)  # leave the canvas -> released
    viewer.page.wait_for_timeout(1500)
    p = viewer.page.evaluate("window.__img2live.viewer.getParams()")
    assert abs(p["ParamAngleX"]) < 1.5


def test_idle_motion_animates_and_the_switch_stops_it(viewer):
    viewer.open("idle=1&blink=0&physics=0&camera=head")
    a = canvas_pixels(viewer.page)
    viewer.page.wait_for_timeout(1500)
    b = canvas_pixels(viewer.page)
    assert np.any(a != b, axis=2).mean() > 0.002, "idle motion should move the picture"
    viewer.page.get_by_role("switch", name="Idle motion").uncheck()
    viewer.page.wait_for_timeout(1500)  # idle contribution fades out
    c = canvas_pixels(viewer.page)
    viewer.page.wait_for_timeout(700)
    d = canvas_pixels(viewer.page)
    assert np.any(c != d, axis=2).mean() < 0.0005, "picture must be still once idle motion is off"
    p = viewer.page.evaluate("window.__img2live.viewer.getParams()")
    assert abs(p["ParamAngleX"]) < 0.05 and abs(p["ParamBreath"]) < 0.01


def test_auto_blink_closes_the_eyes(viewer):
    viewer.open("idle=0&blink=1&physics=0&camera=head")
    low = viewer.page.evaluate(
        """async () => {
          const c = window.__img2live.controller;
          c.idle.triggerBlink();
          let lo = 1; const t0 = performance.now();
          while (performance.now() - t0 < 900) { await new Promise(requestAnimationFrame); lo = Math.min(lo, c.getParam('ParamEyeLOpen'), c.getParam('ParamEyeROpen')); }
          return lo;
        }"""
    )
    assert low < 0.1


def test_reset_button_restores_defaults(viewer):
    viewer.open(make_shots.QUIET)
    make_shots.set_params(viewer.page, {"ParamAngleX": 20, "ParamMouthOpenY": 1, "ParamEyeLOpen": 0})
    viewer.page.get_by_role("button", name="Reset parameters").click()
    make_shots.settle(viewer.page)
    p = viewer.page.evaluate("window.__img2live.viewer.getParams()")
    defaults = {q["id"]: q["default"] for q in puppet_json()["params"]}
    for k, v in defaults.items():
        assert p[k] == pytest.approx(v, abs=1e-6), k
    assert float(viewer.page.locator('input[data-param="ParamAngleX"]').input_value()) == pytest.approx(0, abs=1e-6)


def test_opacity_override_and_wireframe_from_the_renderer_api(viewer):
    viewer.open(make_shots.QUIET + "&camera=head&bg=white")
    before = canvas_pixels(viewer.page)
    viewer.page.evaluate("() => { const { renderer, model } = window.__img2live; renderer.setMeshOpacity(model.meshIndex.get('front_hair'), 0); }")
    make_shots.settle(viewer.page)
    hidden = canvas_pixels(viewer.page)
    assert np.any(before != hidden, axis=2).mean() > 0.05
    viewer.page.evaluate("() => { const { renderer, model } = window.__img2live; renderer.setMeshOpacity(model.meshIndex.get('front_hair'), null); }")
    make_shots.settle(viewer.page)
    assert np.array_equal(before, canvas_pixels(viewer.page))
    viewer.page.evaluate("window.__img2live.renderer.setWireframe(true)")
    make_shots.settle(viewer.page)
    wire = canvas_pixels(viewer.page)
    assert np.any(before != wire, axis=2).mean() > 0.02


def test_mount_api_baseurl_onparams_showlayers_and_destroy(viewer):
    viewer.open(make_shots.QUIET)
    res = viewer.page.evaluate(
        """async () => {
          const { mountViewer } = await import('/js/viewer.js');
          const host = document.createElement('div');
          host.style.cssText = 'position:fixed;left:0;top:0;width:700px;height:500px;z-index:9';
          document.body.append(host);
          const calls = [];
          const v = await mountViewer(host, { puppetUrl: '/sample/puppet.json?cache=1', baseUrl: '/sample', showLayers: false,
                                              onParams: (p) => calls.push(p), initial: { idle: false, blink: false, physics: false } });
          v.setParam('ParamAngleX', 12);
          await new Promise((r) => setTimeout(r, 400));
          const out = {
            calls: calls.length, angle: calls.length ? calls[calls.length - 1].ParamAngleX : null,
            layerRows: host.querySelectorAll('.i2l-layer').length, sliders: host.querySelectorAll('input[data-param]').length,
            texErrors: v.renderer.textureErrors.length, api: ['setParam','getParams','resetParams','setCamera','snapshotPNG','startRecording','stopRecording','destroy'].every((k) => typeof v[k] === 'function'),
          };
          v.destroy();
          out.afterDestroy = host.querySelectorAll('canvas').length;
          host.remove();
          return out;
        }"""
    )
    assert res["calls"] > 3 and res["angle"] == pytest.approx(12, abs=0.01)
    assert res["layerRows"] == 0 and res["sliders"] == len(puppet_json()["params"])
    assert res["texErrors"] == 0 and res["api"] and res["afterDestroy"] == 0
    assert viewer.errors == []


def test_texture_urls_outside_the_puppet_origin_are_refused(browser, base_url, tmp_path):
    """puppet.json is user content: a texture pointing at another origin must show an error, not be fetched."""
    bad = puppet_json()
    bad["meshes"][0]["texture"] = "http://127.0.0.1:9/evil.png"
    ctx = browser.new_context(viewport={"width": 1000, "height": 700})
    v = Page(ctx, base_url)
    v.page.route("**/sample/puppet.json", lambda route: route.fulfill(status=200, content_type="application/json", body=json.dumps(bad)))
    v.open(make_shots.QUIET)
    assert v.page.locator(".i2l-banner").is_visible()
    assert "origin" in v.page.locator(".i2l-banner").inner_text().lower()
    assert not any("evil.png" in e for e in v.errors), "the foreign texture must not even be requested"
    ctx.close()


def test_canvas_backing_store_follows_the_device_pixel_ratio(browser, base_url):
    ctx = browser.new_context(viewport={"width": 1000, "height": 700}, device_scale_factor=2)
    v = Page(ctx, base_url)
    v.open(make_shots.QUIET)
    m = v.page.evaluate(
        "() => { const c = document.querySelector('.i2l-canvas'); const r = c.getBoundingClientRect();"
        " return { w: c.width, h: c.height, cw: r.width, ch: r.height, dpr: devicePixelRatio }; }"
    )
    assert m["dpr"] == 2
    assert abs(m["w"] - m["cw"] * 2) <= 1 and abs(m["h"] - m["ch"] * 2) <= 1
    ctx.close()


def test_camera_controls(viewer):
    viewer.open(make_shots.QUIET)
    r = "window.__img2live.renderer"
    fit = viewer.page.evaluate(f"{r}.camera.zoom")
    viewer.page.get_by_role("button", name="Head").click()
    head = viewer.page.evaluate(f"{r}.camera.zoom")
    assert head > fit * 2.5, "head close-up must be much tighter than the full-body fit"
    box = viewer.page.locator(".i2l-canvas").bounding_box()
    cx, cy = box["x"] + box["width"] / 2, box["y"] + box["height"] / 2
    viewer.page.mouse.move(cx, cy)
    viewer.page.mouse.wheel(0, -300)
    make_shots.settle(viewer.page)
    assert viewer.page.evaluate(f"{r}.camera.zoom") > head * 1.2
    before = viewer.page.evaluate(f"[{r}.camera.cx, {r}.camera.cy]")
    viewer.page.mouse.down()
    viewer.page.mouse.move(cx + 80, cy + 40, steps=5)
    viewer.page.mouse.up()
    after = viewer.page.evaluate(f"[{r}.camera.cx, {r}.camera.cy]")
    assert after[0] < before[0] and after[1] < before[1]  # dragging right/down moves the view left/up
    assert viewer.page.evaluate(f"{r}.cameraMode") == "custom"
    viewer.page.mouse.dblclick(cx, cy)
    assert viewer.page.evaluate(f"{r}.cameraMode") == "head"
    assert viewer.page.evaluate(f"{r}.camera.zoom") == pytest.approx(head, rel=1e-6)


def test_no_gpu_work_when_nothing_changes(viewer):
    viewer.open(make_shots.QUIET)
    res = viewer.page.evaluate(
        """() => {
          const { renderer, controller } = window.__img2live;
          renderer.render(controller.values);
          const first = renderer.stats.uploads;
          renderer.render(controller.values);
          const second = renderer.stats.uploads;
          controller.setParam('ParamEyeLOpen', 0.5); controller.step(0.016);
          renderer.render(controller.values);
          const third = renderer.stats.uploads;      // only the meshes that depend on EyeLOpen
          const t0 = performance.now();
          const m = window.__img2live.model; const out = new Float32Array(4000 * 2);
          for (let k = 0; k < 200; k++) { controller.setParam('ParamAngleX', k % 30); controller.step(0.016); for (let i = 0; i < m.meshes.length; i++) m.evaluateMesh(i, controller.values, out); }
          const ms = (performance.now() - t0) / 200;
          return { first, second, third, ms, meshes: m.meshes.length };
        }"""
    )
    assert res["second"] == 0
    assert 0 < res["third"] < res["meshes"] / 2
    assert res["ms"] < 3.0, f"evaluating the whole puppet took {res['ms']:.2f} ms"


def test_context_loss_is_reported_and_recovered(viewer):
    viewer.open(make_shots.QUIET + "&bg=white")
    if not viewer.page.evaluate("!!window.__img2live.renderer.gl.getExtension('WEBGL_lose_context')"):
        pytest.skip("WEBGL_lose_context is not available")
    before = canvas_pixels(viewer.page)
    viewer.page.evaluate("window.__img2live.renderer.debugLoseContext()")
    viewer.page.wait_for_function("window.__img2live.renderer.lost === true")
    viewer.page.wait_for_selector(".i2l-banner:not([hidden])")
    assert "context" in viewer.page.locator(".i2l-banner").inner_text().lower()
    viewer.page.evaluate("window.__img2live.renderer.debugRestoreContext()")
    viewer.page.wait_for_function("window.__img2live.renderer.lost === false")
    make_shots.settle(viewer.page, 4)
    assert viewer.page.locator(".i2l-banner").is_hidden()
    after = canvas_pixels(viewer.page)
    assert np.array_equal(before, after), "the picture must come back identical after a context restore"


# ------------------------------------------------------------------------------------------------ robustness
def test_missing_texture_is_visible_not_silent(browser, base_url):
    ctx = browser.new_context(viewport={"width": 1280, "height": 800})
    v = Page(ctx, base_url)
    v.page.route("**/tex/face.png", lambda route: route.fulfill(status=404, body="nope"))
    v.open(make_shots.QUIET + "&camera=head", expect_ready=True)
    banner = v.page.locator(".i2l-banner")
    assert banner.is_visible()
    assert "face" in banner.inner_text() and "texture" in banner.inner_text().lower()
    chip = v.page.locator(".i2l-layer", has=v.page.locator(".i2l-layer-name", has_text="face")).locator(".is-bad")
    assert chip.first.is_visible()
    # the layer is drawn as a magenta/black checker instead of vanishing
    img = canvas_pixels(v.page)
    magenta = ((img[..., 0] > 200) & (img[..., 1] < 40) & (img[..., 2] > 180)).mean()
    assert magenta > 0.005, f"no magenta placeholder found ({magenta:.4f})"
    ctx.close()


def test_bad_puppet_url_shows_an_error(browser, base_url):
    ctx = browser.new_context(viewport={"width": 800, "height": 600})
    v = Page(ctx, base_url)
    v.open("puppet=/sample/does-not-exist.json", expect_ready=False)
    assert v.page.evaluate("document.documentElement.dataset.ready") == "error"
    assert "Could not load the puppet" in v.page.locator(".i2l-fatal").inner_text()
    ctx.close()


def test_webgl2_missing_message(browser, base_url):
    ctx = browser.new_context(viewport={"width": 800, "height": 600})
    ctx.add_init_script(
        "const orig = HTMLCanvasElement.prototype.getContext;"
        "HTMLCanvasElement.prototype.getContext = function (t, ...a) { return t === 'webgl2' ? null : orig.call(this, t, ...a); };"
    )
    v = Page(ctx, base_url)
    v.open(expect_ready=False)
    assert v.page.evaluate("document.documentElement.dataset.ready") == "error"
    assert "WebGL2" in v.page.locator(".i2l-fatal").inner_text()
    ctx.close()


def test_capability_report_is_rendered(viewer):
    viewer.open()
    cap = puppet_json()["meta"]["capability"]
    rows = viewer.page.locator(".i2l-cap-item")
    assert rows.count() == len(cap)
    n_deg = sum(1 for v in cap.values() if str(v).startswith("degraded"))
    n_off = sum(1 for v in cap.values() if str(v).startswith("unavailable"))
    assert viewer.page.locator('.i2l-cap-item[data-level="degraded"]').count() == n_deg
    assert viewer.page.locator('.i2l-cap-item[data-level="unavailable"]').count() == n_off
    assert viewer.page.locator(".i2l-badge").filter(has_text="Degraded").first.is_visible() if n_deg else True
    text = viewer.page.locator(".i2l-cap").inner_text().lower()
    assert "blink" in text and "mouth open" in text


def test_every_param_has_a_slider_and_every_mesh_a_layer_row(viewer):
    viewer.open()
    puppet = puppet_json()
    assert viewer.page.locator("input[data-param]").count() == len(puppet["params"])
    assert viewer.page.locator(".i2l-layer").count() == len(puppet["meshes"])
    names = viewer.page.locator(".i2l-layer-name").all_inner_texts()
    orders = [int(x) for x in viewer.page.locator(".i2l-layer-order").all_inner_texts()]
    assert orders == sorted(orders)  # listed in draw order
    assert sorted(names) == sorted(m["id"] for m in puppet["meshes"])


def test_destroy_removes_everything(viewer):
    viewer.open()
    n = viewer.page.evaluate("() => { window.__img2live.viewer.destroy(); return document.querySelectorAll('canvas').length; }")
    assert n == 0
    viewer.page.wait_for_timeout(200)
    assert viewer.errors == []


# ------------------------------------------------------------------------------------------------ (5) mobile
@pytest.mark.parametrize("size", [(390, 844), (360, 740)])
def test_mobile_viewport_has_no_horizontal_overflow(browser, base_url, size):
    ctx = browser.new_context(viewport={"width": size[0], "height": size[1]}, device_scale_factor=2, is_mobile=True, has_touch=True)
    v = Page(ctx, base_url)
    v.open(make_shots.QUIET)
    m = v.page.evaluate(
        "() => ({ sw: document.documentElement.scrollWidth, iw: window.innerWidth, bw: document.body.scrollWidth,"
        " cols: getComputedStyle(document.querySelector('.i2l-viewer')).display,"
        " canvasW: document.querySelector('.i2l-canvas').getBoundingClientRect().width,"
        " panelX: document.querySelector('.i2l-panel').getBoundingClientRect().left,"
        " canvasBottom: document.querySelector('.i2l-canvas-wrap').getBoundingClientRect().bottom,"
        " panelTop: document.querySelector('.i2l-panel').getBoundingClientRect().top })"
    )
    assert m["sw"] <= m["iw"], m
    assert m["bw"] <= m["iw"], m
    assert m["panelTop"] >= m["canvasBottom"] - 1, "single column: the panel sits below the canvas"
    assert m["canvasW"] <= m["iw"]
    # also with the layer list and capability report expanded (they hold the longest strings)
    v.page.evaluate("document.querySelectorAll('details').forEach((d) => (d.open = true))")
    assert v.page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
    assert v.errors == []
    ctx.close()


def test_desktop_layout_is_two_columns(viewer):
    viewer.open()
    m = viewer.page.evaluate(
        "() => ({ cx: document.querySelector('.i2l-canvas-wrap').getBoundingClientRect().right,"
        " px: document.querySelector('.i2l-panel').getBoundingClientRect().left,"
        " sw: document.documentElement.scrollWidth, iw: window.innerWidth })"
    )
    assert m["px"] > m["cx"] - 1 and m["sw"] <= m["iw"]


# ------------------------------------------------------------------------------------------------ screenshots
def test_screenshots(browser, base_url):
    """Review images for humans: bench/outputs/viewer_shots/*.png (see make_shots.py)."""
    from PIL import Image

    files = make_shots.take_all(browser, base_url, SHOTS)
    names = {f.name for f in files}
    for required in (
        "02_head_rest.png", "03_head_yaw_p30.png", "04_head_yaw_m30.png", "05_head_pitch_p30.png", "06_head_roll_p25.png",
        "07_eyes_closed_head.png", "08_gaze_right_head.png", "09_mouth_open_head.png", "10_hair_sway_head.png",
        "11_wireframe_head.png", "15_mobile_top.png",
    ):
        assert required in names, required
    rest = np.array(Image.open(SHOTS / "02_head_rest.png").convert("RGB")).astype(int)
    for f in files:
        img = Image.open(f)
        assert img.size[0] > 100 and img.size[1] > 100
    # poses must differ from rest (the rig actually moves)
    for name in ("03_head_yaw_p30.png", "04_head_yaw_m30.png", "05_head_pitch_p30.png", "06_head_roll_p25.png", "07_eyes_closed_head.png", "09_mouth_open_head.png"):
        pose = np.array(Image.open(SHOTS / name).convert("RGB")).astype(int)
        assert np.abs(pose - rest).max(axis=2).mean() > 0.3, name
